### ISSUE TITLE
Create a Style Pattern Lab

### ISSUE THREAD

**Issue by ryankanno** [CodeforHawaii/projects#3]
https://github.com/pattern-lab/patternlab-php

https://gitlab.com/itawebservices/lacitypatterns/

https://github.com/balmoreboterolacity/lacitypatterns

**Comment by jongeyer** [comment]
Forked patternlab-php made initial commit to github/codeforhawaii/patternlab

In the patternlab hierarchy I've really only gone through the atoms and molecules. So there's still lots to be done: organisms, templates and pages.

While I'm not done rolling out the styles, I will need feedback on what blocks should added / removed and if anyone has thoughts on how things should look.
